package.json
task.js
yarn.lock

Don't create happo reports for empty runs
In case we're not recording any happoScreenshots during a test run, it
makes no sense to have Happo process things and create a report.
This might fix an issue we're seeing at Lightstep where a POST to the
happo.io API fails with a `missing requestIds` message.

Handle empty runs better

---

.circleci/config.yml
.gitignore
bin/happo-cypress.js
package.json
src/loadHappoConfig.js
task.js

After a lot of debugging and exploration, I've landed in a fix for the
problem where a Cypress run creates multiple happo reports, one per test
file.
This was first reported last week and to begin with I couldn't repro it.
In short, this was the bug:
When you have multiple test files, Happo creates one report per file,
instead of one combined report.
When running with `cypress open`, the `after` hook was only called once
per full run. But if you ran `cypress run`, the behavior changed to
calling `after` once per test file. There's a bug for this in the
Cypress issue tracker: https://github.com/cypress-io/cypress/issues/5160
To mitigate this, I tried hard to find a place/hook or something where
Cypress would tell me one of these things:
The full suite is done, or
These are the specs in the …

Add happo-cypress wrapper command

---

index.js
src/createAssetPackage.js
task.js

This PR should fix #5. 
We can't assume assets are located on the same origin as what's defined as the `baseUrl` in cypress.json. Instead, we always have to look them up with the document's base url (`document.location.origin`).

Resolve assets base

---

cypress/integration/home_page_spec.js
index.js
task.js

This will allow people to limit the number of targets for which they
generate screenshots. This is similar to what we do for Happo Examples:
https://docs.happo.io/docs/examples#limiting-targets

Add `targets` option to `happoScreenshot`

---

.circleci/config.yml
.happo.js
bin/happo-cypress.js
cypress.json
cypress/integration/second_page_spec.js
src/resolveEnvironment.js

I'm adding support for a `happo-cypress finalize` command, which will be
used for test suites that execute in parallel. Before I work on the
finalize command, I want to make sure I can run parallel Cypress runs.
The second cypress run will show up as a "Happo (parallel)" build
status (eventually).

Add Cypress run that execute in parallel

---

.circleci/config.yml

Now that we have two separate runs (one serial and the other parallel),
we can optimize builds a little by combining them in the same job and
reusing the install phase.

Simplify and speed up cypress runs

---

cypress/integration/home_page_spec.js
index.js
pages/index.js
public/global.css

This commit will make sure that happo-cypress users can screenshoot
canvases. These are dynamically painted to, and there's no information
in the DOM about what they contain. So we take the canvas and convert it
to a PNG file.

Inline canvases as PNG images

---

cypress/integration/home_page_spec.js
index.js
pages/index.js

If we come across a canvas with an external image, and the CORS settings
of the external image isn't allowing it to be pixel-inspected, the call
to ctx.toDataURL() will fail with a SecurityError. We can catch this
error, log a warning and simply move along.

Don't attempt to inline tainted canvases

---

bin/happo-cypress.js

When running Happo alongside Percy in a Cypress run, we end up confusing Percy to post payloads to our internal server.

Fix incompatibilites with Percy

---

package.json
src/createAssetPackage.js
task.js

This commit will split out assets package handling from the full payload
into a separate call. This will allow us to reuse assets between
snap-requests and will make the individual snap-request payloads smaller
since assets are no longer baked in with them.

Upload assets separately from the snapshots payload

---

index.js
pages/index.js
public/global.css

When inlining canvases, we were calling getComputedStyle to get all the
styles from the canvas over to the image. That worked well if the screen
size is static, but on responsive setups that becomes a problem. Since
getComputedStyle contains width and height, the inlined image will be
statically sized after the canvas at the size it was rendered in the
cypress test, which might be a larger or smaller size than what it would
render as in other screen sizes.

Be less aggressive about copying over canvas styles

---

package.json
src/createAssetPackage.js
yarn.lock

Some users need to proxy all outgoing traffic when running Cypress. It
already has support for a forward proxy via HTTP_PROXY:
https://docs.cypress.io/guides/references/proxy-configuration.html
We can tag along the same setup here. For requests made by the happo.io
library we're using the `request` module, which already supports
HTTP_PROXY. We just need to patch node-fetch, as described in this
issue:
https://github.com/node-fetch/node-fetch/issues/195

Allow setting a HTTP_PROXY environment variable

---

bin/happo-cypress.js

I was debugging why environment variables weren't working in a windows
environment and found that the PATH variable was never passed along with
the command.
Found a solution here:
https://stackoverflow.com/questions/37459717/error-spawn-enoent-on-windows
Making this conditional on OS seems like the safest option here.

Use shell when spawning on Windows

---

src/createAssetPackage.js
src/fetch.js
task.js

I recently added support for setting a HTTP_PROXY, but I managed to miss
that we were fetching stylesheets via a fetch call as well. This commit
unifies all fetch calls into a module, which makes it so that we can set
the proxy settings in a single place.

Proxy link[href]s as well

---

src/createAssetPackage.js
task.js

We're trying to debug an issue where the happoTeardown call times out
after 60 seconds. I have a feeling something is silently failing,
causing the whole thing to stall, and in order to find out I'm adding
some more logging.

Add more debug logs

---

pages/index.js
src/createAssetPackage.js

We've seen this error in the wild:
[HAPPO] Fetching asset from https://<redacted>/#shadow — storing as undefined
ArchiverError: entry name must be a non-empty string value
at Archiver.append (/root/project/js/webapp/node_modules/archiver/lib/core.js:559:24)
at /root/project/js/webapp/node_modules/happo-cypress/src/createAssetPackage.js:96:17
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async Promise.all (index 6)
at async /root/project/js/webapp/node_modules/happo-cypress/src/createAssetPackage.js:104:5 {
message: 'entry name must be a non-empty string value',
code: 'ENTRYNAMEREQUIRED',
This error is causing happoTeardown to silently fail (times out after 1
min).
We can fix this by ignoring these asset urls.

Prevent fetching assets for `url(#ref)`

---

pages/_document.js
public/fonts/fonts.css
public/global.css
src/createAssetPackage.js
src/makeAbsolute.js
task.js
test/makeAbsolute-test.js

If a css file is referencing an asset using a relative path, e.g.
"url(../fonts/foo.woff)", we weren't including the asset correctly in
the assets package. By improving how we resolve these assets we can make
sure that images, fonts, etc are included in the screenshots.

Resolve relative paths in css files

---

index.js
package.json
yarn.lock

This commit addresses #31. That issue describes this error being thrown
when upgrading to Cypress v5:
```
crypto.createHash is not a function
```
While I haven't been able to reproduce this issue myself, it's a little
surprising that the crypto module is available in the browser that
Cypress runs. I'm switching to a browser-safe md5 implementation
instead, which I'm hoping will resolve the issue.

Avoid using `crypto` module in browser

---

index.js
package.json

I'm trying to debug an issue where the html+css payload is very large in
some cases. After debugging, I found that the css collected for certain
test suites can contain multiple copies of the same styles. By tagging
css that's already been collected, we should be able to avoid the
duplication.

Don't collect css that's already been processed

---

pages/index.js
src/createAssetPackage.js

I'm debugging a case where an asset is using an empty string as the src
url. The asset package fails somewhat silently with an error log and the
happoTeardown call times out.
We can ignore these assets as they won't work anyway. While I was at it,
I made the createAssetPackage function reject when an archiver error
happens. This will help users as the error will be propagated to the
Cypress process.

Ignore assets without urls

---

task.js

This fixes a bug where if you use `cypress open` and run the same test
twice in a row you'll end up with component variants being incorrect:
default-2 instead of default
large-2 instead of large
etc
In 711eb197, I removed the reset of the knownComponentVariants variable
since it messed up reports when using the happo-cypress wrapper. That
commit introduced the issue fixed here. We have to be careful about
resetting and only do it in the non-wrapper case, otherwise we might end
up with invalid reports.

Reset knownComponentVariants when report is created

---

.gitignore
index.js
package.json
src/createAssetPackage.js
task.js
yarn.lock

This commit will hopefully resolve a timeout issue with
happoRegisterSnapshot (most likely) related to large snapshots with
inlined canvases. Instead of keeping the base64 url in the assets list,
we can eagerly send it in a new happoRegisterBase64Image task, store it
to disk and let the asset package simply pull in the image on disk. This
should help keep the main happoRegisterSnapshot payload smaller, which
I'm hoping will make it succeed more often. It also makes the in-memory
footprint smaller since the base64 images are discarded sooner.
For now I'm keeping a .happo-tmp folder around. I might make an effort
to automatically clean it up at some point in the future but I want to
make sure this fix is the right one first.

Send inlined canvases separately from snapshot

---

index.js
pages/index.js

Yesterday I was debugging issues on our happo-snap workers. For some
reason, asset packages were containing entries where the file name was a
data uri. I tracked this down to the happo-cypress module. If an image
is using a data-uri it would be included in the list of urls sent to
createAssetsPackage. If the request made to download the image resulted
in a 200 response, that content would be included in the assets package.
I fixed this issue on our workers by inspecting the zip package and only
extracting ones that we know are okay.
By filtering out data uris before we send them to the happo task, we can
get rid of this problem from the source.

Don't include data uris in asset packages

---

cypress/integration/home_page_spec.js
index.js
pages/index.js

I'm working on a change to happo workers that will make them honor a
`data-happo-scrollposition` attribute. This attribute can be used to
restore scroll positions as they were when the DOM snapshot was taken,
at screenshot time.

Register scroll positions

---

task.js

A customer reached out and was confused about Happo running for each
time they ran tests locally. This is quite a gotcha, and can lead to
quota/cost issues down the line.
The right thing to do is to disable Happo by default and only run it
when explicitly asked for (via the wrapper). I thought about adding a
configuration option somewhere to enable the old behavior but decided an
env variable was enough, as this is more of a per-run setting.

Disable Happo by default when running `cypress open`

---

pages/_document.js
pages/index.js
public/subfolder/styles.css
src/makeAbsolute.js
test/makeAbsolute-test.js

If a css file was located in a subfolder, e.g.
http://foo.bar/assets/css/styles.css, and referenced assets absolutely,
e.g. /assets/images/foo.png, they would not work. This was because we
simply appended the path to the baseUrl. To make things work, we need to
grab the image from the origin root.

Fix loading images referenced from subfolder css files

---

src/resolveEnvironment.js
test/resolveEnvironment-test.js

A new experimental feature has been added to happo.io where you can
specify` __LATEST__` as the before sha, and it will pick the latest
(approved) report to compare against. This should help people testing
out happo with cypress, as they will much quicker get a useful dashboard
and see diffs.

Compare with latest report in dev mode

---

cypress/integration/home_page_spec.js
cypress/integration/second_page_spec.js
index.js
pages/index.js

This function can be used to hide certain elements that are known to
cause spurious diffs. The defaults include:
- Leaf elements with "time ago" text, e.g. "12 days ago", "3 minutes
ago".
- <time> elements
You can append selectors via a `selectors` option and matchers (regexes)
with `matchers`.

Add cy.happoHideDynamicElements function

---

pages/index.js
src/makeAbsolute.js
test/makeAbsolute-test.js

I got a report from a customer who had updated to 1.12.1 where it would
crash trying to resolve an asset referenced via ./asset.png. Turns out
we didn't handle this case well.

Fix resolving assets referenced with ./

---

cypress/integration/home_page_spec.js
task.js

To make it easier to map the Happo browser targets to the viewports used
in the Cypress tests, we're making it possible to inject Happo targets
at runtime.
We're piggy-backing on the `targets` option here. If the target is a
string, use as before (limiting the screenshot to that target). If it is
an object, we merge it with the current .happo.js targets, then limit to
the new target.
Being able to dynamically add targets at runtime will make the Cypress
run better coupled to the Happo screenshots, and there's less risk for
them getting out of sync. Often times, dynamic targets will be
constructed automatically from Cypress runtime properties.

Add support for dynamic targets

---

cypress/integration/bigcanvas_spec.js
pages/big-canvas.js

We're seeing the happoRegisterBase64Image task time out for an
account. Their canvases are quite big, so I suspect there's a oom issue
of some sort here. Going to add a large canvas to our test suite to see
if it causes CI to fail the same way for us.

Add example of a big canvas

---

index.js
package.json
src/chunked.js
src/convertBase64FileToReal.js
task.js
yarn.lock

The total size of the base64 package sent to the
happoRegisterBase64Image can be quite large, and we're seeing occasional
task timeouts (most likely because the task process runs out of memory
and exits). To mitigate this, I'm sending the base64 image in chunks.
Each chunk is appended to a file in the file system, and as a last step
the base64 file is converted to a real file (using streams to prevent
reading large things into memory).

Chunk up saving the base64 image

---

index.js
src/makeAbsolute.js
test/makeAbsolute-test.js

Our previous use of doc.location.origin as the base url caused issues
when you were on a page with a path, e.g.
http://host.domain/foo/index.html
and had a relative path to a stylesheet, e.g.
themes/bar/styles.css
We ended up resolving the path to the css as
http://host.domain/themes/bar/styles.css, which is incorrect -- we need
the path involved in the base url as well.

Fix resolving relative assets in non-root documents

---

cypress/integration/spa_spec.js
index.js
pages/hello.js
pages/subfolder/hello.js
public/subfolder/hello.css

In a single-page-application, the document you land on will dynamically
change its location with history.pushState. This leads to a problem when
downloading relative assets, if the original document is in a different
sub path than the tests. Take this example:
Start page is loaded at url "/".
Link "admin" is clicked.
Page "/admin/start" is loaded.
A happo screenshot is taken.
If any css was added in the initial page load, and it has a relative
path (e.g. "styles.css", or "./styles.css"), the screenshot will be
missing those styles. To fix this, we need to "remember" the baseUrl for
style elements (including <link>). We do this by subscribing to the
"window:load" event from Cypress and setting the baseUrl as a property
on all css elements found right at the start.
This isn't a fool-proof …

Resolve styles from right baseUrl in SPA

---

cypress/integration/iframe_spec.js
cypress/support/commands.js
index.js
pages/iframed.js

This commit fixes an issue where taking a screenshot of an iframe body
would result in no styles being present in the screenshot. This is
because we were assuming that all elements and styles were present in
the root cypress document. By grabbing the document relative to the
element we're working with, we can make screenshots of iframe content
look better.
Please note that this doesn't fix the issue where taking a screenshot of
some element that wraps an iframe results in the iframe being empty.
This commit will only make it so that you can dive into an iframe and
select elements (including <body>) inside.

Find document from subject element

---

index.js

I was debugging a test suite and noticed that some javascript executed
on Happo workers when injecting the html into the page. It turns out
that there were script tags in the recorded html that referenced
external scripts (on a CDN). We don't want to double-execute these
scripts. Since scripts are executed once when running the test suite,
having them execute again will only lead to confusion.

Remove script tags when recording html

---

index.js
pages/_document.js
public/global.css
task.js

I'm working on a change to happo workers which makes these attributes
come in play (get injected at render time). This will help resolve test
suites where some element depends on attributes from the html or body
element for its styling.

Send html and body attributes in payload

---

bin/happo-cypress.js
src/resolveEnvironment.js

Support for fallback shas to use as the baseline was added earlier this
year for the main happo.io library [1]. But the happo-cypress library was
never updated. I just had a support issue where someone was trying to
compare using a different base branch than master, and they were getting
confusing results.
Fallback shas take precedence over Happo's default way of resolving
baseline reports from the main/default branch.
I was a little confused to see that the format for fallbackShas passed
to compareReports was expected to be "raw" and that string splitting
happened late. Not going to worry about that right now, but might be
worth making the interface a little nicer.
https://github.com/happo/happo.io/blob/8bf7980a69572066fec6daf81c0a1249d50e6051/src/commands/compareReports.js#L27
[1] …

Send fallback shas to Happo server

---

src/resolveEnvironment.js
test/resolveEnvironment-test.js

Previously, we were sending fallbacks that included the current
beforeSha commit. This could potentially work but it wasn't how I
intended to do things initially. Plus, that's not how the happo.io
library does it (which is what I tried to mimic):
https://github.com/happo/happo.io/blob/8bf7980a69572066fec6daf81c0a1249d50e6051/bin/happo-ci#L25

Resolve fallback shas from before beforeSha

---

task.js

I've been chasing a bug with the following error for a while now:
`cy.task('happoTeardown')` timed out after waiting `60000ms`.
It's been happening to a few customers, but never with a consistent
repro case. I finally saw it happen locally and got some debug logs I
could look at, and from what I can see it looks like the node process
that happoTeardown runs in simply stalls/crashes silently:
[HAPPO] Done uploading assets package, got { path: 'a/8/bfe0333567ebb1f8ebbe1485cb18c7dd.zip' }
[HAPPO] Sending snap-request(s) for target=chrome-large
[HAPPO] Sending snap-request(s) for target=firefox-large
[HAPPO] Sending snap-request(s) for target=safari-large
[HAPPO] Sending snap-request(s) for target=edge-large
[HAPPO] Sending snap-request(s) for target=ie-large
[HAPPO] Sending snap-request(s) …

Create snap-requests serially

---

.circleci/config.yml
.happo.js
cypress/plugins/index.js
cypress/support/commands.js
index.js
package.json
task.js
yarn.lock

This PR adds support for having screenshots produced directly from the Cypress test run instead of sending over DOM snapshots to happo.io.

Add support for local snapshots

---

.github/workflows/cypress.yml
cypress/integration/second_page_spec.js
cypress/plugins/index.js
index.js
task.js

If a test is automatically retried, happo would duplicate snapshots that
were part of the retry and add a counter suffix to the variant name,
e.g. "foo-bar-1".
To fix this, I've made us listen to the after:spec event, then inspect
each test to look for failed attempts. If a failed attempt is found, we
delete all snapshots made during the duration of the failed attempt. I'm
making the assumption that timestamps will be in sync between the
browser process and the background node process. This could be
dangerous, but I couldn't find a better alternative to associate
snapshots with a test attempt.
Because of the added after:snapshot event handler, I'm changing the
initialization process:
happoTask.register(on)
This is a breaking change, so in order to help people upgrading without
updating …

Remove retried snapshots before sending to happo.io

---

package.json
yarn.lock

The docs informs users to install happo-e2e separately, so having happo-e2e listed in dependencies will most likely mean that two versions will get installed.
Moving to a peer dependency means we can make updates to happo-e2e separately from this package.

Move happo-e2e to peerDependencies

---

cypress/integration/home_page_spec.js
index.js
package.json
yarn.lock

This option will make the screenshot include all elements that matches the selector (the subject of the `happoScreenshot` call) when taking the DOM snapshot. Requires version happo-e2e@2.2.0 or later.

Add support for `includeAllElements: true` option for happoScreenshot

---

.npmignore

`44M	./node_modules/happo-cypress/.next/` which is not ideal, AFAIU this app is needed only for tests.
Not sure how npm packaging works, but I suppose this PR would skip the directory.

Don't add `/.next` to the resulting NPM package

---

.circleci/config.yml
cypress/integration/home_page_spec.js
index.js

To help clean up the Cypress command log, we can allow people to pass in `log: false` when calling Happo commands.
I've cleaned up some options usage so that we consume the known options to us and then pass along all others to cy.task. This will allow people to also use `timeout` and potential future options as well. https://docs.cypress.io/api/commands/task#Arguments
Fixes https://github.com/happo/happo-cypress/issues/111

Allow logs to be hidden

---

package.json
yarn.lock

We need to update happo-e2e to 3.3.0+ to get the new snapshotStategy feature. I'm bringing happo.io along for the ride.

Update happo-e2e 2.4.0 to 3.3.1, happo.io 6 to 11

---

cypress/integration/home_page_spec.js
index.js
pages/index.js

Similar to `localSnapshots: true`, we want people to be able to use the new "clip" snapshot strategy that happo-e2e has made available.
https://docs.happo.io/docs/cypress#locally-produced-images
The clip strategy means the whole dom is included in the snapshot, and happo workers will clip the screenshot based on where the `[data-happo-clip]` element is located.

Allow snapshot strategy to be configured
